version: '3.8'

# 僅用於開發環境測試用
services:
    # PHP-FPM service
    php:
        image: php:8.2-fpm
        container_name: laravel_php
        volumes:
            - .:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        ports:
            - "8000:8000" # PHP's built-in server will be exposed on port 8000
        command: php -S 0.0.0.0:8000 -t /var/www/html/public
        networks:
            - laravel

    # MySQL service
    mysql:
        image: mysql:8.0
        container_name: laravel_mysql
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel

# Docker Networks
networks:
    laravel:
        driver: bridge

# Volumes
volumes:
    mysql_data:
        driver: local
